# Generated by Django 3.1.7 on 2021-03-02 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Records',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('gender', models.CharField(max_length=50)),
                ('ageGroup', models.CharField(max_length=50, null=True)),
                ('isActive', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'ids',
            },
        ),
    ]
